version: "3.8"

services:
  # ──────────────────────────
  # React + Vite front-end (with HMR) 
  # ──────────────────────────
  web:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app:delegated
      - /app/node_modules
    ports:
      - "5173:5173"               
    command: >
      sh -lc "
        corepack enable &&
        pnpm install &&
        pnpm exec vite --host 0.0.0.0 --port 5173
      "