version: "3.8"

services:
  # ──────────────────────────
  # React + Vite front-end (with HMR) 
  # ──────────────────────────
  web:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ../web:/app:delegated
      - /app/node_modules
    ports:
      - "3000"
    command: >
      sh -c "
        corepack enable &&
        pnpm install &&
        pnpm dev -- --host 0.0.0.0
      "