name: Deploy Web (S3 + CloudFront)

on:
  # Keep only a manual trigger so nothing runs automatically.
  workflow_dispatch:

permissions:
  contents: read

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow is disabled
        run: |
          echo "This workflow is intentionally disabled."
          echo "Uncomment the original content below and restore 'on.push' to re-enable."

# ===================== ORIGINAL WORKFLOW (COMMENTED OUT) =====================
# name: Deploy Web (S3 + CloudFront)
#
# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:
#
# permissions:
#   contents: read
#
# jobs:
#   deploy-static-site:
#     runs-on: ubuntu-latest
#     environment: production
#
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4
#
#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v2
#         with:
#           aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region:            us-east-1
#
#       - name: Install dependencies & build
#         run: |
#           corepack enable
#           pnpm install --frozen-lockfile
#           pnpm run build
#
#       - name: Sync build to S3
#         env:
#           SITE_BUCKET: ${{ secrets.SITE_BUCKET_NAME }}
#         run: |
#           aws s3 sync dist/ s3://$SITE_BUCKET/ --delete
#
#       - name: Invalidate CloudFront cache
#         env:
#           DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
#         run: |
#           aws cloudfront create-invalidation \
#             --distribution-id $DISTRIBUTION_ID \
#             --paths "/*"
# =============================================================================
